export const CASE_STUDIES = [
  {
    name: "Jobstm",
    prefix: "",
    value: 2.4,
    suffix: "x",
    label: "Acceleration in hiring lifecycle",
    problem: "Gig recruitment platforms lose users to complex sign-ups and fake-profile anxiety.",
    stack: ["Expo", "React Native", "Next.js", "Express", "PostgreSQL", "AWS", "Razorpay"],
    preview: "/case-studies/jobstm.png",
    url: "https://jobstm.co",
  },
  {
    name: "Sustainext",
    prefix: "",
    value: 70,
    suffix: "%",
    label: "Friction reduction for enterprise audits",
    problem: "Enterprise carbon-emission logging was manual, error-prone, and buried in dashboards.",
    stack: ["Next.js", "OCR Pipelines", "LLM Classification", "SSR"],
    preview: "/case-studies/sustainext.png",
    url: "https://sustainext-udm.sustainext.ai",
  },
  {
    name: "Sole & Ledger",
    prefix: "<",
    value: 10,
    suffix: "s",
    label: "Transaction flow design",
    problem: "Laggy retail billing software caused checkout queues and stock mismatches.",
    stack: ["Next.js", "TypeScript", "NextAuth", "PostgreSQL", "bwip-js", "pdf-lib"],
    preview: "/case-studies/sole-ledger.png",
    url: "https://funkyfashion.shop",
  },
  {
    name: "Aadidhara",
    prefix: "+",
    value: 35,
    suffix: "%",
    label: "Growth in direct producer revenue",
    problem: "Multi-layered agri supply chains cut farmer margins and hurt buyer trust.",
    stack: ["Next.js", "TypeScript", "Tailwind CSS", "Razorpay", "Framer Motion"],
    preview: "/case-studies/aadidhara.png",
    url: "https://aadidhara.com",
  },
] as const;
